use_frameworks!

platform :ios, '10.0'

target 'DeviceImpressSwift_Example' do
  pod 'DeviceImpressSwift', :path => '../'

  target 'DeviceImpressSwift_Tests' do
    inherit! :search_paths

    
  end
end
